### ISSUE TITLE
Video freeze

### ISSUE THREAD

**Issue by joekh** [svtek/VideoSplashKit#9]
On iOS 9, when you open the app, the video loads normally, if you click on the home and then reopen the app, the video freezes

**Comment by toygar-zzz** [comment]
Fixed. Thanks @joekh  :+1:

**Comment by joekh** [comment]
Great :+1:

**Comment by LiveRock** [comment]
I am still facing this problem. The video freezes when coming beck from background.

**Comment by sahin** [comment]
@LiveRock we will try to reproduce it.
